<template>
    <form :action="send_url" :method="send_method" @submit.prevent="send">
        <slot name="form-errors">
            {{ form_errors.join(', ') }}
        </slot>
        <slot name="autogenerated-items">
            <section v-for="(field, key) in form_fields" :key="key">
                <FormItem :ref="field.name" v-model="form_fields[key].value" :field="field"/>
            </section>
        </slot>
        <slot name="additional-items"/>
        <v-btn type="submit" primary color="primary">
            Send
        </v-btn>
    </form>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'
import FormItem, { FieldInterface } from '@/components/FormItem.vue'

interface FormInterface {
    form_errors: string[];
    fields: FieldInterface[];
}

@Component({
    components: {
        FormItem,
    },
})
export default class Form extends Vue {
    @Prop({type: Object, default: () => ({}) })
    readonly source_form!: FormInterface
    @Prop(String)
    readonly send_url!: string
    @Prop({type: String, default: 'get'})
    readonly send_method!: string

    private form_fields: FieldInterface[] = this.source_form.fields || []
    private form_errors: string[] = this.source_form.form_errors || []

}
</script>
